### ISSUE TITLE
Update drush command in Vagrant.

### ISSUE THREAD

**Issue by jibran** [nickschuch/vd8#12]
After `vagrant ssh` `which drush` outputs `/usr/bin/drush` which is 5.7 version of drush. Either we can replace this symbolic with /vagrant/bin/drush or updated vagrant drush to master.

**Comment by tregismoreira** [comment]
@jibran this tutorial helped me: https://drupalize.me/blog/201408/upgrading-drush-work-drupal-8.

**Comment by jibran** [comment]
This has been fixed a while back.
