### ISSUE TITLE
Update PHP 5.5 to PHP 5.6

### ISSUE THREAD

**Issue by jibran** [nickschuch/vd8#39]
```
d8 /vagrant(master *): php -v
PHP 5.5.28-1+deb.sury.org~trusty+1 (cli) (built: Aug 16 2015 09:30:05) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```
Can we please update it to 5.6?

**Comment by benjy** [comment]
Or PHP 7 :)

**Comment by jibran** [comment]
Well the idea is to work on commonly available version. Because of outdated version I have some issues on my current VM. Some tests are failing for apparently no reason.

**Comment by jibran** [comment]
In latest release of https://atlas.hashicorp.com/pnx/boxes/lamp 0.0.8 updated the php from 5.5 to 5.6 but now we can update it to PHP7 as https://atlas.hashicorp.com/pnx/boxes/lamp70 is published. See https://github.com/nickschuch/vd8/pull/41 for that.
